name    'ptomulik-macro'
version '0.0.9'
source 'git://github.com/ptomulik/puppet-macro.git'
author 'ptomulik'
license 'Apache License, Version 2.0'
summary 'Define and evaluate macros in puppet manifests'
description 'Define and evaluate macros in puppet manifests'
project_page 'https://gitbub.com/ptomulik/puppet-macro'
